# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperID', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(max_length=512)),
                ('abstract', models.CharField(max_length=4096)),
                ('publishDate', models.DateField()),
                ('paperUrl', models.URLField()),
                ('documentApproved', models.BooleanField()),
                ('abstractApproved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('queryID', models.AutoField(primary_key=True, serialize=False)),
                ('queryString', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('poolSize', models.IntegerField()),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('result', models.CharField(max_length=2048)),
                ('paperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysrev.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastViewed', models.DateTimeField()),
                ('forename', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('institution', models.CharField(choices=[('UOG', 'University of Glasgow'), ('GCU', 'Glasgow Caledonian University'), ('GSU', 'Glasgow Strathclyde University'), ('EDI', 'Edinburgh University'), ('UWS', 'University of Western Scotland'), ('STU', 'St.Andrews University'), ('OXF', 'Oxford University'), ('CAM', 'Cambridge University'), ('OTH', 'Other')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('relevant', models.BooleanField()),
                ('notes', models.CharField(max_length=4096)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysrev.Query')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysrev.Researcher')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysrev.Researcher'),
        ),
    ]
