# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0002_auto_20160319_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
